crate/cloud-docs

- .github/workflows/docs.yml
> RTD: Switch default branch to `main`

- .github/workflows/docs.yml
> CI: Update a few details in the CI configuration

- docs/reference/subscription-plans.rst
Plans were updated, 8 GiB storage per node now
> Fix crfree and cr0 resources

- docs/reference/subscription-plans.rst
> Add shared product cloud docs

- docs/tutorials/full-text.md
- docs/tutorials/index.md
- docs/tutorials/object.md
- docs/tutorials/quick-start.md
- docs/tutorials/time-series.md
Some suggestions about wording, punctuation, and active voice, based on lost changes during review/merging of GH-33.
> Cloud Tutorials: A few wording adjustments

- docs/index.md
- docs/reference/services.md
Add page describing our service offerings.
relates to https://github.com/crate/cloud/issues/1436
> Add services page

- docs/tutorials/time-series.md
Few suggestions on wording taken from https://crateio.atlassian.net/wiki/spaces/TeamDBCloud/pages/518422599/Time-Series+Analyzing+Weather+Data
> Wording adjustments on time-series tutorial

- docs/reference/overview.rst
> Added a note about how Parquet works.

- docs/reference/api.rst
Add note that login is required to access API docs
> Add note that login is required to access API docs

- docs/reference/services.md
- docs/reference/subscription-plans.rst
Reflect cpu changes in dedicated plans
> reflect cpu changes in dedicated plans

- docs/tutorials/index.md
- docs/tutorials/time-series-advanced.md
- Time-series tutorial with metadata integration
- Adaptation of index.md in tutorials section
> Advanced time-Series tutorial with metadata integration

- docs/_extra/cratedb-edge-cluster-dashboard.json
- docs/_extra/cratedb-edge-logs-dashboard.json
- docs/index.md
- docs/reference/glossary.rst
- docs/reference/overview.rst
- docs/reference/subscription-plans.rst
- docs/tutorials/deploy/marketplace/subscribe-aws.rst
- docs/tutorials/deploy/marketplace/subscribe-azure.rst
- docs/tutorials/edge/custom-backup.rst
- docs/tutorials/edge/index.rst
- docs/tutorials/edge/introduction.rst
- docs/tutorials/edge/managed-kubernetes.rst
- docs/tutorials/edge/monitoring.rst
- docs/tutorials/edge/self-hosted-edge.rst
Rename CrateDB Edge to CrateDB Cloud on Kubernetes.
A bit quick and dirty, but we agreed to not put too much effort into it :)
> Rename CrateDB Edge to CrateDB Cloud on Kubernetes

- docs/howtos/visualize-data-with-grafana.rst
- docs/tutorials/integrations/metabase.rst
More reference fixing, not sure where these came from: https://readthedocs.org/projects/crate-cloud/builds/23723184/
> Link fixes

- pull_request_template.md
Tiny fix for the template, there were missing spaces. Check boxes were not functional because of that.
X
X
> Fix `pull_request_template.md`

- docs/tutorials/time-series-advanced.md
- docs/tutorials/time-series.md
For adding dividers better conveying "What's Inside" each subsection of the "Data Analysis" section, i.e. which feature is demonstrated, use [Sphinx' "rubric" directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-rubric).
- https://crate-cloud--65.org.readthedocs.build/en/65/tutorials/time-series.html#analyzing-data
- https://crate-cloud--65.org.readthedocs.build/en/65/tutorials/time-series-advanced.html#time-series-analysis-with-metadata
> Tutorials: Improve layout on Time Series tutorials

- docs/index.md
Just a few ideas about the »**About CrateDB Cloud**« topic in general, to better convey **What's Inside**, intending to provide **better guidance**.
https://crate-cloud--58.org.readthedocs.build/en/58/
Try to add some fresh air, with phrases from others doing similar business. They can't be that wrong?
If you like the idea, please support us shaping it by adding your comments and suggestions, or approving. Thanks!
~~Not all details need to go into the final version, and alternatively, the PR might be closed without further ado if there is no interest or capacities to improve this topmost section of the cloud documentation.~~
~~Another possibility is that the content will go elsewhere, but our intention was to conceive it for the topmost explainer area. In the end, everything is possible, …
> Guidance: Expand main explainer text about CrateDB Cloud

- docs/reference/overview.md
Small fix for the region table in Reference
https://crate-cloud--67.org.readthedocs.build/en/67/reference/overview.html#basics
- Fix for the region table in Reference
> Fix the region table

- docs/tutorials/edge/index.md
Fix for reference
https://crate-cloud--73.org.readthedocs.build/en/73/
> Small visual fix

- docs/howtos/create-org.md
Just a note about maximum number of organisations a user
> Add note for maximum number of organizations

- docs/reference/services.md
- docs/tutorials/quick-start.md
Update suspension interval to 4 days
> Update suspension interval to 4 days

- docs/index.md
- docs/reference/billing.md
- docs/reference/index.md
Overhaul billing page to reflect all current changes in the billing ares.
https://crate-cloud--78.org.readthedocs.build/en/78/
> Overhaul billing page

- docs/requirements.txt
No need to nail dependencies any longer.
> Dependencies: crate-docs-theme==0.34.0 has been released
